CREATE TABLE [dbo].[tblResponse]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [QuestionId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES dbo.tblQuestion(Id), 
    [AnswerId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES dbo.tblAnswer(Id), 
    [ResponseDate] DATETIME NOT NULL
)
